import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FooterNavigation } from "./components/FooterNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className="bg-[#2C2C2C]">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#2C2C2C]`}>
        <div className="min-h-screen">
          {/* メインコンテンツ */}
          <div>
            {children}
          </div>

          <FooterNavigation />
        </div>
      </body>
    </html>
  );
}
